### ISSUE TITLE
Normative language

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#10]
The current instantiation of the spec uses SHOULD statements liberally. These are less testable than SHALLs and every SHOULD is an opportunity for interop to fail.  Request is to review the document in light of this and to consider if there are SHOULDs that would be better off as SHALLs.

**Comment by RufaelDev** [comment]
Some care was taken to NOT have interop fail for the SHOULD cases, in essence the protocol is simple baseline (HTTP POST + fmp4 or HTTP POST + DASH/HLS) many of the added features are nice to have/best practice but not necessarily fundamental to interoperate, correct media/metadata fmp4 with a post should suffice for profile 1, while DASH/HLS with correct POST behavior should suffice for profile 2, nevertheless in the next review this can be double checked, much of the other features are needed for a best practice not necessarily to interoperate

**Comment by RufaelDev** [comment]
to be further discussed in next draft in detail

**Comment by RufaelDev** [comment]
I will close this issue as the review period gave sufficient time to raise specific issues and text has been improved in revisions
