### ISSUE TITLE
Make explicit that IDR frame inserted at splice point shall be signaled as sync-sample

### ISSUE THREAD

**Issue by boy-vd** [Dash-Industry-Forum/Ingest#107]
In point 9h of section 5.6 it is stated that an IDR frame needs to be inserted at a splice point:

> In the case of 9, For SCTE-35 ingest the schemeIdURI in the DASHEventMessageBox MUST be urn:scte:scte35:2013:bin as defined in [SCTE214-1]. A binary scte-35 payload is carried in the message_data field of a DASHEventMessageBox. The DASHEventMessageBox must conform to [SCTE214-1]. If a splice point is signalled, the SCTE-35 SpliceInsert command SHALL be used. **In this case, media tracks MUST insert an IDR frame at the time corresponding to the event presentation time.**

My proposal is to make this statement more explicit by adding that the IDR frame must be signaled as being a sync-sample. 

My understanding is that paragraph 9.2.6 of the CMAF specification already covers this requirement, but from experience I know that this is not the default behavior of some major encoders when inserting IDR frames at the moment. 

Making this requirement more explicit might help.

**Comment by RufaelDev** [comment]
tf 2019 17th: make this clear in the new section

**Comment by RufaelDev** [comment]
new section was added  on splicing explicitly addressing this issue
