### ISSUE TITLE
ingest demo and reference code

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#108]
proposed reference code with sample cmaf files to ingest:
https://github.com/unifiedstreaming/fmp4-ingest/tree/master/ingest-tools
- source code works
- sample cmaf files are available 
- node.js receiver still needs more work

note: consider only the ingest part and not the event processing part

working demo with unified origin and the reference code using docker: 
https://github.com/unifiedstreaming/cmaf-ingest-demo
- demonstrates the functionality

proposal: 
accept the reference software in DASH Industry Forum

**Comment by RufaelDev** [comment]
tf 2019 17th postpone decision, discuss with board

**Comment by acbegen** [comment]
Could we add a section in the spec titled "Open-Source Implementation" and provide the link to the code, etc.?

**Comment by RufaelDev** [comment]
This is already in the document, some more review and testing and feedback would still be welcome.
