### ISSUE TITLE
sequence number of fragments

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#109]
The text should be updated:
The fragment sequence numbers seq_num of fragments in the CMAFstream signalled in the tfhd SHOULD arrive in increasing order for each of the different tracks/streams that are ingested. Using both timestamp baseMediaDecodeTime and seq_num based indexing will help the Receiving entities identify discontinuities. In this case sequence numbers SHOULD increase by one.

should be mfhd and explicitly reference the usage of seq_num as present in the mfhd box based on section 8.8.5.2 of ISOBMFF specification

**Comment by TobbeEdgeware** [comment]
@RufaelDev  I suppose you refer to 5.2 point 11.

In my view, this needs to be further elaborated like this:

The first seq_num in each segment should increase
seq_num of fragments inside a segment should increase by 1.

However, the first seq_num in segment N should not be forced to be bigger than the seq_num of the last fragment of segment N-1. 

The reason for this is that seq_num is 32-bit, and many packagers use the epoch time 1970-01-01 as AST, and then an increment every 0.36s leads to overflow already today.

With an increase of seq_num every second there will not be an overflow until 2106.

Is this your understanding as well?

**Comment by TobbeEdgeware** [comment]
A solution to the issue of just having a 32bit sequence number is to let it wrap-around. By just adding that it may happen, I think we should be fine with saying that it should always increase. For tfdt, we explicitly don't allow wrap-around, but instead one must change from 32-bits to 64 bits when needed.

**Comment by RufaelDev** [comment]
addressed already this can be closed, the wrap-around, we have not said anything about wrap around but the recommendation is only a should
