### ISSUE TITLE
Set some expectations for detecting and flagging encoder clock drift

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#11]
The output of the packager should be 1 second of data per second. Ref https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/231

There are encoders out there that fail to conform to this and produce data at a slightly different rate, e.g. 1.001 seconds of data per second. I anticipate IOP requiring services to sort this out and fix any bad timing.

Packagers do not have good tools for doing any such fixes: what they can really do is just start a new period, skipping a segment if there was data overflow from the encoder or inserting a 1-segment padding period if there was underflow. I do not expect that packagers will be able to do sample-level corrections or to generate padding segments on the fly - this is only something the encoder could do.

This period-level fixing of bad timing would not lead to a positive user experience but is necessary to ensure timing model consistency.

A far better solution would be to have encoders properly track real time. To encourage encoder authors to fix broken encoders, there needs to be feedback available to them that this problem exists. I see an opportunity here to include this aspect in the ingest protocol - to raise an alarm when such problems are detected.

I propose that the ingest specification require packagers to report an error to the encoder when timeline overflow or underflow is detected. This would require at least the following:

* A definition for how to detect overflow or underflow.
* A feedback mechanism that the packager can use to report errors to the encoder.

Timeline consistency is a factor that applies across a long time span and many segments, whereas the ingest protocol current draft is rather more focusing on the transmission of individual segments. Therefore I realize this is not an obvious fit into the protocol. However, the fact remains that live encoding must be time-synchronized. If the protocol currently does not carry this notion, it should likely be extended to do so.

To be clear, I am talking of encoder clock drift that occurs over 10 hours or 10 days, not about timing variations in the delivery of a single segment.

For the moment, I have no specific proposal on this topic, just this request/goal to provide as input for the ingest task force.

**Comment by RufaelDev** [comment]
Encoder clocks should be updated according to respective protocol NTP, PTP in such 24/7 setups, alternatively the timing in the input might be re-used such as from the SDI. The ingest spec cannot define a new synchronization model, it mainly re-used the cmaf synchronization model. Yes encoders should produce content with consistent fragment duration, but if slightly different there is no other option for the packager to work with that, as long as it does not occur frequently and the timing information and media is correct.

**Comment by sandersaares** [comment]
I am not talking about fragment duration - I think fragment duration is not relevant to this topic.  It is a question of the amount of timeline filled per second (which should be 1 second).

Yes, ideally everything is time-synchronized and operates in 1:1 time but the ingest protocol should also ensure that something desirable happens when the encoders are operating imperfectly. In the current situation, I would like to see some sort of error condition occur when this happens. Imperfect timing needs to result in a signal to the operators that something is wrong.

I am not an ingest expert, so it is hard for me to say how exactly such signals should occur. It is my hope that the ingest task force does have the required expertise to do something about this, however.

**Comment by RufaelDev** [comment]
summary of discussion:
1. receiver is not well placed to tell encoder if it is behavior correct
2. Api of the  devices could be used to monitor encoder/packager
3. separate issue for the delay/connection stats reporting
4. do we need a backchannel for the ingest ?
