### ISSUE TITLE
brand for the last segment

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#114]
This issue was created based on the MPEG exploration on this topic. 

consider adding a brand for signalling the last segment e.g.`lmsg`

**Comment by RufaelDev** [comment]
Question, what would the receiver do with this ? Not accept any more inputs on this track/representation ?

**Comment by GuillaumeBichot** [comment]
The receiver knows it is a clean end and not error case: i.e. does not need to react/get segments from the backup server.

**Comment by RufaelDev** [comment]
Nov. 20 
two important things for the reciever 
- knows that it is not an error no need to go to backup server 
- TCP connection 
- in case of resume new TCP connection and initialization segment would need to be sent 
- would there be additional restrictions  on the init segment ? 
AP sollicit more detailed text try to close/progress at next cycle

**Comment by RufaelDev** [comment]
Dec 11th: consider also the chunking cases, so the lmsg may be in the styp of last chunk. With single post per segment case it could also be in the first styp. Consider closing at next cycle.

**Comment by RufaelDev** [comment]
- In low latency it may be in the chunk 
- Sometimes you will only know at the end that the stream is finished
- legacy aproach was mfra which we want to deprecate 
- may need another solution for ll case if any proposal
- consider if it is important enough

**Comment by RufaelDev** [comment]
feb 26th ad with restriction, mfra is deprecated

**Comment by RufaelDev** [comment]
addressed in https://github.com/Dash-Industry-Forum/Ingest/pull/143
