### ISSUE TITLE
recommend avc3 / hev1 (should) instead of avc1 hvc1 (may)

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#115]
This issue was created based on the MPEG exploration on this topic. 

This may make sense as avc3/hev1 are more flexible and therefore more suitable for live content. avc1/hvc1 are essentially a subset.  Consider updating 5.3.8 and 5.3.9 accordingly

**Comment by GuillaumeBichot** [comment]
ok

**Comment by RufaelDev** [comment]
Nov. 20th 
probable agreement recommendation makes sense 
ffmpeg supports both, but bitstreams look more like avc3/hev1 even if avc1/hv1 is signalled 
try to close at next call

**Comment by RufaelDev** [comment]
I think this is ok for ingest, but in practice avc3 is less supported as compared to avc1, so perhaps some note around this can be added in the specification text.

**Comment by RufaelDev** [comment]
Resolution: prefer avc3 hev1 on ingest, add text for creating the transmux as avc1 is still the more supported for clients/dai/browsers. For long running live streams changing resolutions/can happen i.e. changing pps, and avc3 hev1 can support this. Packager can do conversion to avc1 if needed. avc3/hev1 is typically preferred but avc1 is also possible. This is the reason that for 24x7 live ingest avc3/hev1 is preferred but avc1/hvc1 is also perfectly viable solution if you don't need this, e.g. for short running live events for example.

**Comment by RufaelDev** [comment]
addressed in: https://github.com/Dash-Industry-Forum/Ingest/pull/143
