### ISSUE TITLE
common encryption

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#117]
This issue is created based on the mpeg exploration on this topic.

Consider allowing common encryption, in case of 5.3.1, it is not recommended as transport layer securty can be used and origin may not have means to decrypt, this was discussed in Dash-Industry-Forum/Ingest#23

**Comment by RufaelDev** [comment]
For combining this may make some sense, but how would the receiver obtain a key and license server information ? Secondly, storing a track with common encryption may not be what you want as mistakes and errors may corrupt your media archives which can be quite painfull. Common encryption is not as robust as other techniques for encryption available for general purposes. 
Is the goal by enabling this to achieve transport layer security or just to avoid doing encryption later on in the distribution to client phase ?

**Comment by GuillaumeBichot** [comment]
Agree that managing license +keys at the receiver sounds too much.

**Comment by RufaelDev** [comment]
Nov 20. 
- packagers don't usually ingest encrypted content 
- cpix has such a feature but not widely adopted (content based encryption)
- deriveable key by agreement between parties 
no strong support for common decryption at the packager, 
document atleast this fact that there is no standard api for getting the decryption key. 
we cannot make this work for packager ingest for this reason.

For passthrough (interface 2) this may work, but not for re-packaging.

**Comment by ZmGorynych** [comment]
1. "Encryption at rest" or "encryption in flight" is often a requirement, and it is not fulfilled sufficiently by TLS alone (especially when we store something, even temporarily). If you disallow this, you just made the protocol irrelevant for many deployments.
 
2. All operations we need to perform on a segment can be performed on encrypted content. Conversion to MPEG-2 TS or Matroska are the only ones which cannot.

3. You are free to use content in the clear, you just do not want to disallow encryption support. If you want an interoperable baseline, require receiver-side ClearKey support but allow use of other DRMs instead.

**Comment by RufaelDev** [comment]
Jan 29th. agreement , It seems reasonable to also allow cenc as in some cases this is contractually required and we may not want to limit such cases out, also compatility with other CDN ingest may be better. Specification should mention both options and cases.

**Comment by RufaelDev** [comment]
included in PR https://github.com/Dash-Industry-Forum/Ingest/pull/143
