### ISSUE TITLE
add text on redundant encoder sync

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#118]
This issue was created based on the MPEG exploration on this topic

add text on redundant encoder usage such as based on using shared timeline origin and fixed duration fragments

**Comment by AUGxhub** [comment]
this is an issue, currently, most subtitle filled by mp4 box container has no valid tfdt value, which cause a lot of problems

**Comment by RufaelDev** [comment]
comment from nicolas weil on 13th november call
- epoch locking with fixed segment duration
- idr frame in the segments with emsg box signalling scte

**Comment by RufaelDev** [comment]
#126

**Comment by GuillaumeBichot** [comment]
I guess it means, like with ATS, the coders (main, backup) must be synchronized (IDR at the same picture, wall clock).

**Comment by RufaelDev** [comment]
In the case of more than one redundant media sources, synchronization between them can be achieved as follows. A fixed segment duration is chosen such as based on the fixed GoP duration e.g. 2 seconds that is used by all media sources. The media sources use a fixed anchor T as a timeline origin, this could be the Unix Epoch 1-1-1970 or another well known defined time anchor. The segment boundaries in this case are  K * segment duration (since anchor T) for an integer K > 0. Any media source joining or starting can compute the fragment boundary and produce segments with equivalent segment boundaries corresponding to approximately the current time by choosing K sufficiently large. It is assumed that encoders generate signals from a synchronized source and can use timing information from this source e.g. MPEG-2 TS presentation time stamp or SDI signals to compute such timestamps for each segment. For example in the case of MPEG-2 TS program clock reference (PCR) and presentation time stamps can be used. Based on this different media sources will produce segments with identical durations, timestamps and enclosing frames. This allows different media sources to join and leave and synchronized operation, enabling both synchronization and redunancy.

**Comment by RufaelDev** [comment]
#126 will do this
