### ISSUE TITLE
requesting segments from a third server 

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#119]
This issue was created based on the MPEG exploration of this topic

Consider adding text on requesting redundant segments from a third server. Consider if this is in scope,
this may be added as a recommendation/best practice ?

**Comment by AUGxhub** [comment]
u can use 301 redirect and Access-Control-Allow-Origin tech to make it

**Comment by ZmGorynych** [comment]
@AUGxhub:  No. The use cases are loss of input and loss of encoder. I don't see how a 301 will help you here -- the encoder is  either out of alignment (if you lost input mid-segment) or dead. Dead encoders do not respect 301's :-)

@RufaelDev: I would add it as a recommended practice

**Comment by RufaelDev** [comment]
Jan 29. Agreement, mention this in the text as a recommended practice, but the signalling for this will not be in scope, unless a concrete proposal is made.

**Comment by RufaelDev** [comment]
included in https://github.com/Dash-Industry-Forum/Ingest/pull/143
