### ISSUE TITLE
Define track synchronization

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#12]
I was not able to find text in the ingest protocol on how the packager is supposed to synchronize different tracks it is ingesting. This seems like a critical interoperability point and should be covered by the ingest protocol.

There is a diagram 9 with some descriptive text that briefly mentions synchronization but I do not understand it well. Is it meant to be some informative example use case? It does not read as anything normative.

There seems to be an assumption near diagram 9 that tracks must already use synchronized timing when generated by encoder. I think this might indeed work well as the underlying principle but needs to be clearly spelled out as the required and only mechanism. Or if altrentive mechanisms are also desired, the selection of the mechanism should be part of the ingest protocol as it is an important interoperability point.

I do see synchronization mentioned in failover section but this is a far bigger topic than failover and really should not be related to failover at all. Timing should be a universal concept. I also request it be more clearly spelled out as it is not clear what the statement in the failover section really requires, it just says "must be synchronized" in essence. More is needed - this is just the goal, the protocol needs to say more like what fields must match under what conditions, how mismatches are to be resolved or even detected, possibly give examples of suitable synchronization mechanisms (I imagine the exact mechanism can be flexible of course).

**Comment by RufaelDev** [comment]
Track synchronization should use the CMAF synchronization model for synchronization of tracks, this should probably be emphasized more in the text, CMAF has a model for synchronization of tracks, however we do not require each stream to start from timestamp zero as this relates to live streams. So the spec needs synchronized encoders, these can output fragments with well defined duration, timescale and synchronized timestamps. Based on timestamps and/or sequence numbers and respective time scales and durations tracks can be synchronized. I will update the text to contain more information about the synchronization of encoders and tracks beyond the section about failovers

**Comment by RufaelDev** [comment]
Threshold define: sample accuracy (based on the timescale which might be different for audio video) , first proposal: lower than half the sample duration

**Comment by RufaelDev** [comment]
closing issue, sample accuracy on timescale will be a requirement
