### ISSUE TITLE
Tighten up section 4

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#122]
The text in this section should be tightened up a little bit 
- 1. Allow POST or PUT
- Remove redundant text try to keep it short
- HTTP Error codes perhaps consider a separate section, usually the ingest source reacts 
the same way on any error code 403 or 4xx anyway

**Comment by RufaelDev** [comment]
created pull request for review https://github.com/Dash-Industry-Forum/Ingest/pull/123

**Comment by ZmGorynych** [comment]
Is there any reason to allow both POST and PUT? Let's select just one.

**Comment by acbegen** [comment]
Further tighten-up in PR 143.

**Comment by RufaelDev** [comment]
mar 12 not needed as this time as already included in https://github.com/Dash-Industry-Forum/Ingest/pull/143
