### ISSUE TITLE
replace Streams() keyword with something more DASH like

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#125]
It is proposed to deprecate the usage of Streams() and Switching() to something better aligned with DASH.

Initial proposal: 

The URI contains a representation id identifier that can be detected as follows
dash-if-cmaf-repid-[identifier]-
dash-if-cmaf-switch-id-[identifier]- 
identifier = [a-z|A-Z|0-0]+  identifier only uses these URL safe characters [a-z|A-Z|0-9|=]+ 

This way an encoder configuration can configure the segement names to contain information about the 
representation and switchingset.

for example using  DASH representation id 
\<Representation
        id="dash-if-cmaf-repid-video_eng=96000-dash-if-cmaf-switch-id-1-"
        bandwidth="96000"
        scanType="progressive">
\</Representation\>

and segment template: 

 \<SegmentTemplate
        timescale="12800"
        initialization="cmaf-ingest-$RepresentationID$.dash"
        media="cmaf-ingest-$RepresentationID$-$Time$.dash">
        \<SegmentTimeline\>
          ........
        \</SegmentTimeline\>
 \</SegmentTemplate\>

Would allow detection of the representation ids and 
switchingset ids via a simple pattern search or regular expression.

In this case the switchingset id would be 1 and the representation id is video_eng=96000

If agreed we can fine tune the specific text.

**Comment by ZmGorynych** [comment]
I would reference the URI spec and require use of URI-safe characters as defined in RFC3986 (see https://tools.ietf.org/html/rfc3986#section-2.3)

Also:
1. If segments are not compatible with CMAF, they should be "bmff" for ISO-BMFF. I am concerned about requiring CMAF conformance when neither HLS nor DASH strictly requires it in practice; let alone the whole issue of codec profiles.
2. Use of RFC 3986 will disallow use of  `video_eng=96000`, and we would rather use `video_eng_96k`. The `=` breaks things if for some reason someone wants to use query parameters to convey extra information
3. _Please_ don't use ScanType. It is always progressive by default, it should only appear in case we have something interlaced.

**Comment by RufaelDev** [comment]
@ZmGorynych  thanks for the feedback
1. ok lets use another keyword as CMAF maybe dash-if-ingest-rep dash-if-ingest-sw, maybe a structured naming pattern is even better  and avoid very specific keywords ?
e.g. contentType_repid_ssid_bitrate  as a recommendation for the representation id field  ?
2. as video_eng=96000 etc are often used do you think there is another alternative option that would be less intrusive ?  
3.  OK

**Comment by RufaelDev** [comment]
Jan 29th 2021 
briefly looked at it, more input is welcome

**Comment by RufaelDev** [comment]
feb 12th call

- initial idea is good but we need more input from the community 
- allow for appending to the fixed structure 
- avoiding keyword probably, allow custom section 

AP. develop this more, maybe send an e-mail to ingest list

**Comment by RufaelDev** [comment]
A simple proposal


If the receiver has no other means to identify the representation of a segment,
a fixed naming structure shall be used to allow receiver to identify segments.

The fixed naming structure fixes the naming of the RepresentationID and of the media and initialisation segments.

*RepresentationID* 

A simple example representation id based on fixed naming combines 5 values enclosed by {, the { not 
being part of the representation id: 

represenation_id = {repid}-{asid}-{bandwidth}-{contentType}-{language} 

all values enclosed by {} are URI safe characters as per  RFC3986  and shall not contain '-'

language is as set in lang attribute, or may be und (undefined) if not set or set to und
contentType is as set in the adaptationSet, may be audio, video, text, meta, unknown (if not set) 
bandwidth is as set in the representation element 
asid is the adaptationset id, or zero otherwise 
repid may be an additional identifier for the representation
 
 
*Intialisation Segment*

The initialisation segment shall end with $RepresentationID$ and a filename 
extension separated such as .m4s or .dash by a dot (.) e.g.

Init-$RepresentationID$.ext 

*Segments* 

The segments shall end with -$RepresentationID$-$Time$ or -$RepresentationID$-$Number$ and a filename 
extension such as .m4s or .dash separated by a dot (.)  e.g.

Segment-$RepresentationID$-$Time$.ext

**Comment by RufaelDev** [comment]
Feb 19th 

bandwidth in this case is static as set in the Representation Element

- ask for feedback especially encoder vendors
- if agreed in principle refine the 
- leave open for now

**Comment by RufaelDev** [comment]
mar 12: added a note in the document around the text. In parallel, progress this in the coming week and try to include this either in this issue, or in the document (with a note that it needs feedback and review) .

**Comment by kjerbi** [comment]
On behalf of ATEME:
we encourage suggestion to change current format. Using this format : representation_id = {repid}-{asid}-{bandwidth}-{contentType}-{language} , we might need to add the resolution (applies only for video) as for the same bitrate we can have more than one resolution. 
Also does 'asid' refer to switching id here?

**Comment by RufaelDev** [comment]
I changed a bit the proposal, I removed language (it may contain a - between language tags contradicting), 
I put the content type at the end to avoid possible conflict between the initialisation
segment and the media segments (with -0). As follows:

The representation id of the representation shall be defined as:

representation_id = {repid}-{asid}-{bandwidth}-{resolution}-{contentType}

Where {contentType} is as set in @contentType the AdaptationSet, 
it may be audio, video, text, meta, unknown (if not set)
and {bandwidth} is as set in the representation@bandwidth 
asid is the AdaptationSet@id, or zero otherwise 
repid may be an additional identifier to guarantee uniqueness in the AdaptationSet. 

resolution may be set to 0 if not defined such as 
for representations that do not have a resolution.

all values enclosed by {} are URI safe characters as per RFC3986 and shall not contain '-'

Initialisation Segment

The initialisation segment shall end with $RepresentationID$ and a filename
extension separated such as .m4s or .dash by a dot (.) e.g.

Init-$RepresentationID$.ext

Media segments

The segments shall end with -$RepresentationID$-$Time$ or -$RepresentationID$-$Number$ and a filename
extension such as .m4s or .dash separated by a dot (.) e.g.

Segment-$RepresentationID$-$Time$.m4s or Segment-$RepresentationID$-$Time$.dash

**Comment by RufaelDev** [comment]
June 25th call: initial consensus, text needs more detailed review

**Comment by RufaelDev** [comment]
September 3 good to make it a recommendation, recommendation would not be a hard recommendation in some cases when an mpd is used it may not be a hard recommendation,  {repid}-{asid}-{pid}-{mpd_id}, bandwidth contenttype may be also in representation id maybe another separator or other reserved character. Content type should be in the mimetype. 
lets think a bit more on the different options

**Comment by RufaelDev** [comment]
getting some more feedback from implementors, and also following nicolas comment, perhaps restricting the MPD for CMAF 
ingest is better then defining a very specific naming convention. Following some example MPD from implementors.

I propose the following text, so alternative to Streams() keyword can be used, but you need an MPD with some
restrictions that I feel are inline with what many encoders are producing today (or capable to produce) 

Manifest with minimumUpdatePeriod set to a large value, this way 
sender need not continuously update the MPD.
Availability start time should be 1970-01-01T00:00:00Z

each AdaptationSet (or otherwise each individual Representation) shall contain a SegmentTemplate element

SegmentTemplate@initiatization shall contain the substring $RepresentationID$
SegmentTempate@media shall start with the substring $RepresentationID$ 
and also contain the substring $Number$ or $Time$ (not both). 

Representation@bandwidth shall be set to a correct value. 
BaseURL element shall be absent 
The manifest contains only a single period with @start PT0S

Each DASH Representation represents a CMAF track
Each DASH AdaptationSet represents a CMAF SwitchingSet 

This way each segment can be explicitly mapped to the CMAF track and/or SwitchingSet

**Comment by RufaelDev** [comment]
17 september -> representationID may also not be only in the beginning, change at the start to shall include

**Comment by RufaelDev** [comment]
Keep the naming cross periods, allow naming to be added. MPD update discussion for a next revision.

**Comment by RufaelDev** [comment]
16. The MPEG-DASH manifest shall use SegmentTemplate in each AdaptationSet 
       (or in each contained Represention). 
         a. The SegmentTemplate@initiatization in the MPEG-DASH manifest 
            shall contain the single substring $RepresentationID$ and the
            SegmentTempate@media shall contain the single substring $RepresentationID$ and
            the substring $Number$ or $Time$ (not both). 
         b. SegmentTemplate@media and @initialization shall be identical for each 
            SegmentTemplate Element in the MPEG-DASH manifest.
         c. The BaseURL element shall be absent.
         d. The AvailabilityStartTime SHOULD be set to 1-1-1970 (Unix epoch) 
            and the period @start to PT0S (if this is not the case it may be more difficult to 
            synchronize more than one ingest source). 
         e. Each Representation in the MPEG-DASH manifest represents a CMAF track, 
            each AdaptationSet in the MPD represents a CMAF SwitchingSet.
         f. In case an ingest source issues an HTTP Request with an updated MPEG-DASH 
            manifest, identical naming conventions apply. A receiver may ignore such updated MPD 
            send by an ingest source. 
         g. The MPEG-DASH manifest shall contain only a single Period Element.

**Comment by RufaelDev** [comment]
call 24th consider adding additional epoch example, such as sky-net become self aware
