### ISSUE TITLE
emsg and timed metadata delivery in time

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#127]
Add explicit statement that timed metadata (either emsg or metadata track) shall be transmitted before 
media samples, and be available at the reciever at least 6 seconds before the corresponding media samples.

Thus a metadata intended for media presentation time T shall be available 6 seconds before T at the receiver of the ingest stream.

Currently this notion was implicit, the recommendation is to make it explicit.

**Comment by nicoweilelemental** [comment]
While this might be possible for messages like SCTE-35 markers where some prefetching can be organized, this is not possible for all categories of metadata which are produced in realtime (KLV as per MISB ST 1910 being an example of that) and cannot be defined and transmitted in advance.

**Comment by RufaelDev** [comment]
OK so this would mainly apply for SCTE-35 
we should add some practices for that, two options are:
1. using presentation_time_delta > 0 and sending the scte-marker sooner in an earlier segment
2. sending the segment earlier
would this be something good to add ?

**Comment by RufaelDev** [comment]
12th feb. no further comments, consider adding

**Comment by RufaelDev** [comment]
added in PR https://github.com/Dash-Industry-Forum/Ingest/pull/143
