### ISSUE TITLE
PTS and PCR to DASH timeline

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#131]
Is there a recommended practice for mapping PTS/PCR to a DASH timeline, especially considering we use epoch locking ? 
The PTS/PCR may still be carried in SCTE-35 signals but has no meaning in CMAF/DASH

**Comment by TobbeEdgeware** [comment]
There is no mapping that I'm aware of, but one could tie PTS to be media presentation time in 90kHz clock mod 2^33 in epoch time. Of course, we have the common issue of leap seconds which would mean that TAI (atomic time) would be better.

**Comment by RufaelDev** [comment]
as in https://github.com/Dash-Industry-Forum/Ingest/issues/128 emsg is leading, we dont need to explicitly define the mapping, but we can mention the ingest source is responsible for the conversion, for dash emsg time is leading

**Comment by RufaelDev** [comment]
mar 12. not yet implemented AP: propose some text for this.

**Comment by RufaelDev** [comment]
added this to the text in general requirements
