### ISSUE TITLE
general editorial improvement

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#139]
punctuation, capitalization, spacing, should be improved a bit, check if there is a best practice for these bikeshed documents

**Comment by RufaelDev** [comment]
some discussion on this, lets keep as is for now, and we can do this later, keep open

**Comment by acbegen** [comment]
Addressed pretty much all the issues. Please use what has been adopted in PR 143.

**Comment by acbegen** [comment]
This can be closed.
