### ISSUE TITLE
Issues after PR 143

### ISSUE THREAD

**Issue by acbegen** [Dash-Industry-Forum/Ingest#144]
https://dashif-documents.azurewebsites.net/Ingest/pull/143/DASH-IF-Ingest.html

Things to fix: 
- Section 6.2 clause 7, deprecate mfra
- Update figure 8.
- Check whether POST URL vs publishing URL are correctly used
- There is no MIME type for the .key file, should there be a registration to the IANA
- segmentTimeBuffer?

**Comment by acbegen** [comment]
Still standingL:
> * Section 6.2 clause 7, deprecate mfra
> * Update figure 8.
> * There is no MIME type for the .key file, should there be a registration to the IANA

Completed:
> * Check whether POST URL vs publishing URL are correctly used
> * segmentTimeBuffer?
RFC reference fix.

**Comment by RufaelDev** [comment]
actually this pull request is more comprehensive: 

technical **completed**: 
- section on encoder synchronization added  #126 #140
- single segment per post restriction #112
- text on encoder input loss  #113
- guidance on the manifest formatting #111
- reference to MPEG-B part 18 for timed metadata track  #31
- emsg time is leading clarification #129
- brand for last segment #114 
- deprecate mfra #124 
- allow common encryption of media tracks #117
- text on requesting segments from third server #119
- swap priority preferred sample entry to hev1/avc3 #115
- additional clarification on SCTE-35 carriage #128 #133 #130 #121 #127

technical *todo* 

prft box text #116
constant duration timed metadata #145
text on conversion MPEG-2 TS to DASH timeline #131 
replacement method for Streams(),   #125

Editorial **completed**:
capitalization, cross references fixed, replaced some terms 
for consistency, change references to IETF specifications

**Comment by acbegen** [comment]
> Editorial **todo**:
> 
> * clean up the informative sections a bit
> * update the diagrams where needed

One more thing is to check the clause numbers in the external documents. With new editions, they change occasionally.

**Comment by acbegen** [comment]
Editorial to do after March 18th version:
- update the diagram where needed 
- key file iana registration
- checking clause/section numbers for dash, cmaf, scte, mpeg4-30, etc. specs

**Comment by acbegen** [comment]
After March 23rd:
- key file iana registration

**Comment by RufaelDev** [comment]
24th of september this is also solved in the current version
