### ISSUE TITLE
Response back to the ingest source after POST

### ISSUE THREAD

**Issue by acbegen** [Dash-Industry-Forum/Ingest#146]
Should we define a behavior for the receiving entity here?

**Comment by RufaelDev** [comment]
mar 12. good suggestion, what to put in the response header is not defined as long running post was mainly considered. maybe also add as a question or note in the spec to ask for feedback around this from commerical encoder vendors.

**Comment by acbegen** [comment]
Question for the reviewers has been added to the document.

**Comment by kjerbi** [comment]
On behalf of ATEME:
Currently we open and close a connection on each segment. A regular return of size of tranferred bytes and url is always welcome for additional checking but not indispensable.

**Comment by RufaelDev** [comment]
Some proposed text to add (unless there is more specific proposal on what the respond): 

The receiving entity shall return with an HTTP 200 OK response in case the HTTP POST request was received and processed correctly. If this is not the case error responses following requirements from 5.3 shall be returned. In addition, the response body may contain additional information from the receiving entity such as number of bytes written or other information. The format of such additional body is not defined by this document.

**Comment by RufaelDev** [comment]
call 17th of September. Maybe the transfer time is something of interest ? Maybe define an optional reponse header ? size, time especially in case of chunked transfer this may be usefull. Consider combining this with the information from the encoder, versioning may be added.

**Comment by RufaelDev** [comment]
14. The response from the [=receiving entity=] may, in addition to response code, 
       return information in the response body, such as relating to the transfer time, 
       size etc. of the last HTTP request, especially in case this request was in HTTP chunked 
       transfer mode. But no specific response format is defined at this time, but this
       may be considered in future revisions.

**Comment by RufaelDev** [comment]
call 24th maybe add a note in the version to sollicit input
