### ISSUE TITLE
Encoder MAY resend -> MUST resent

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#15]
There is a statement that encoders MAY resend a segment on reconnect. This just creates room for non-interoperable solutions, doesn't it? It should be a MUST if you feel that resending is potentially useful.

**Comment by RufaelDev** [comment]
Not all encoders do this and we did not want to invalidate existing implementations,  the packager can ignore duplicate segments and fill gaps of missing segments or signal discontinuity, this MAY does not really introduce a source of non-interoperable solutions, it probably just allows a tradeoff between higher quality (resend), versus lower latency, less complexity (no resending) allowing different deployments, key is to resend the init segment, the previous media segments may be resend but it is not strictly necessary

**Comment by sandersaares** [comment]
Different possibilities for operation here just leave room for non-interoperable implementations.

I do not think not invalidating existing implementations can be a goal. This would assume that all existing implementations are interoperable, which does not seem like an assumption that can reasonably be made. DASH-IF is all about creating interoperability and yes, this will mean that some implementations will need to change to be brought up to spec.

**Comment by KevinCJohns** [comment]
One way to address this is to make it mandatory that the receiver be able to handle both cases. If it is optional for the encoder to resend on re-connect, it has to be mandatory for the packager to support receiving the potentially duplicate data vs. not receiving it. I didn't notice that called out in the spec.

**Comment by RufaelDev** [comment]
So how does this give non interoperable implementations, a packager can perfectly account for both options. if I don't get a new segment, i have to make a discontinuity as a packager, if I do get a new segment I can fix this by waiting for this and having a good timeline ? If I want to avoid this at all I use redundant encoders and the resending of extra segment will be discarded ? As long as the packager then throws away the resend segment there is no problem at all and we don't break any backward compatibility at all. I really don't understand this issue, as a packager can deal with this perfectly fine, therefore it is still not clear to me how this inroduces interoperability problems.

**Comment by sandersaares** [comment]
I apply the basic test case of "what happens if I swap out a supposedly interoperable component".

Scenario: I want to make a package that does not experience dropouts due to terminated connection from encoder.

I implement solution with encoder A that implements the ingest protocol. It resends segment. All is well.

I then switch out to encoder B. Suddenly my packager is no longer gapless because encoder B does not resend interrupted segments.

This is what I call non-interoperable behavior. A change in one system forces an undesired change in another or even breaks a feature.

I can see either choice - either resending or not - being a valid choice but I think the ingest protocol should define which way it needs to work. What actually happens should not be a surprise to the packager.

**Comment by RufaelDev** [comment]
Under normal operation this would not happen anyways, there are other ways to solve the problem such as using multiple encoders, improving your infrastructure to fail less, the practice is that not all live encoders resend the fragment and it is not important enough to force them to change this, if you have failing components maybe you need to improve your infrastructure. Discontinuities can be signalled in DASH and both input and output are available in the standardized format. The packager can make its own decision based on how much buffering is allowed. Again this is not an interoperability problem, interoperability is when really bad behavior occurs due to non conforming input, this is not the case here
so it is not an interop problem

**Comment by sandersaares** [comment]
It sounds like we have different definitions of interoperability. Thank you for clarifying your viewpoint. I suppose there is nothing actionable remaining on this topic, is there?

**Comment by RufaelDev** [comment]
OK, I will close the issue, there will be a call on normative language in the second week of January, you can also join it if you like, I will close this issue
