### ISSUE TITLE
Clearly outline requirements for hot failover mode of operation

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#16]
It might be that I misread it but the text seems to consider "failover" as switching from instance A to instance B. This is not necessarily the case.

In some my deployments, I want to always send data to all instances and from all instances of the fault-tolerant component (which may be either encoder or packager). Failover for me means that one instance dies. There is no moment of "switching" involved, just some traffic no longer occurs and client traffic is routed to the surviving instances.

This model does not appear to be well described.

Consider especially if I have two encoders producing data. Both send data to each instance of my packager. That is, packagers receive two copies of each segment in ideal conditions. How is this handled? How is the duplicate de-conflicted? What is the right behavior if my encoders go out of sync for some reason (e.g. simple configuration error so wrong encoder was connected). What if one encoder is a bit slower but still consistent? This will certainly lead to "out of order" scenarios (encoder A sent segment 5, then encoder B sends segment 4).

**Comment by KevinCJohns** [comment]
We really need to provide very concrete requirements as this is an area of much confusion and it is intertwined with the client expectations. DASH expects the client to handle the failover via. multiple base URLs, but the segment info returned by either base URL is expected to be identical, so segment naming needs to be consistent across the two instances. HLS is a bit tricker, the spec allows for multiple URLs, similar to DASH, but that isn't supported by all clients. From our testing, HLS performs best if the data returned from a secondary source is identical. So synchronization and segment naming is critical to building a resilient system. We should require and define how to embed timing data in the source. We then need to define how the Packager names segments such that it meets the constrains laid out by DASH and HLS (typically segment names are epochtime/segmentduration to allow for stateless segment naming across multiple packaging instances). Optionally, the packager can try and clean up the source and re-time it based on system time (using NTP).

**Comment by RufaelDev** [comment]
1. we need more input for profile 2 
2. profile 1 the text should be improved and more discussion is needed
target not for next draft but the one after the next

**Comment by RufaelDev** [comment]
requirements: 
- reconnect in case connection fails without interrupting media timeline
- reconnect in case ingest source fails without interrupting media timeline
- reconnect in case the media processing entity fails without interrupting media timeline
- Allow redundant media processing entities and ingest sources

**Comment by RufaelDev** [comment]
given correspondence of Kilroy adn Kevin on this topic, rediscuss some of this, 

for implemenation guidelines we can recommend using single base_url instead of multiple base_url
