### ISSUE TITLE
Carriage of encryption information should conform to IOP

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#17]
The statement about carriage of encryption information in the draft is quite vague, just pointing to ISOBMFF and MPEGCENC. I suggest requiring IOP as the normative definition, where there is more detail about what must be where - the MPEG specs are too generic for interoperability here.

That being said, the whole topic could be far more explicitly described in the ingest spec.

PS. Do I understand it right that this is only relevant for profile 2? There is no expectation that encoders already provide encrypted data, right? This is only what comes after packaging?

**Comment by RufaelDev** [comment]
encryption will not apply to profile 1 where other forms of security can be in place, for profile 2 based on the discussion, the protocol seems pretty much opaque, it seems mainly about signalling mimetypes and filename extensions, I would assume mpd/presentations would conform to the IOP but not sure it will be explicitly stated as this is already implicit
