### ISSUE TITLE
Disallow HTTP

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#19]
We see no reason to allow HTTP posts due to privacy concerns and would suggest requiring HTTPS usage for all POST operations.

**Comment by RufaelDev** [comment]
Fully agreed, but in some setups these concerns may not apply like an on premise setup where a live encoder and packager need to interoperate, one can use whitelisting/blacklisting in the server etc, HTTPS is strongly recommended and supposed on the spec, but this is why it is a SHOULD in this case

**Comment by KevinCJohns** [comment]
How about we update the verbiage to something along the lines of:
The Encoder and Packager MUST support the use of HTTPS for the transfer of data. HTTPS SHOULD be the default behavior. The use of HTTP should be restricted to managed/private networks only.

**Comment by RufaelDev** [comment]
HTTPS is strongly recommended in current spec, I will close issue
