### ISSUE TITLE
How to handle inband event messages at Profile1?

### ISSUE THREAD

**Issue by cenkd** [Dash-Industry-Forum/Ingest#21]
How to handle only inband messages which don't have any MPD output? Is the assumption that encoders will not send any emsg which doesn't have any MPD output or corresponding stream?

**Comment by RufaelDev** [comment]
This is the assumption yes, instead the packager could generate the inband events for the clients though,
either from the out of band signalling or other factors. So yes, the approach is to use out of band events/metadata, and the packager does not have to scan to find the inband events.  I don't think it is necessary to make sending inband events by the encoder illegal not allowed in the spec, it is just not the approach adopted, I would imagine the packager filtering out these inband events or passing them through in some cases. If you have some explicit examples were such inband events are needed (if they are media track specific for example), please propose the use case.

**Comment by RufaelDev** [comment]
I added a note to the next draft with the following text:

Note: [[!MPEGCMAF]] Has the notion of an inband emsg box to convey,
metadata and event messages inband. In the current specification 
sparse track is used instead to convey such information. 
Advantages of sparse track include avoiding sending duplicate information
in multiple tracks, and avoiding a strong dependency between media 
and metadata by interleaving them. In case the ingest 
source sends an emsg box the receiver SHOULD ignore them.

This implies that emsg boxes could in fact be present in the ingest stream, but that 
this is not the recommended behavior

**Comment by RufaelDev** [comment]
resolution call 16 january: don't allow inband mpd (for safety receiver SHALL ignore them)
