### ISSUE TITLE
Provide a way to Name tracks on ingest of profile 1

### ISSUE THREAD

**Issue by johndeu** [Dash-Industry-Forum/Ingest#22]
In Smooth, we allowed the encoders to deterministically post to a "stream Name" when sending a track in. 
For example, the encoder would post to the {ingestendpoint}/streams(streamName) 

This would allow to redundant encoders to send duplicate streams with the same streamName to the "media processor" and allow it to filter, drop, etc. redundant or past segments.  

It also allows the scenario where you can late bind a new "named" track into the manifest from an application outside of the encoders.  For example, a separate application could be created for "audio commentary" that runs outside of the encoders and sends a new track with the stream name of "commentary" that is appended to the list of tracks in the MPD available on the "Media Processor".

**Comment by RufaelDev** [comment]
This could be done via the adding the /streams(streamName) to the ingest point, would this be sufficient or is there also a need for signalling in the tracks themselves like using some structures of the trackformat ?

**Comment by johndeu** [comment]
We dont have to re-use the /streams name if others dont like that... should try to make it match DASH as best as we can.

**Comment by RufaelDev** [comment]
How about also adding a command for switching set id PostURL/channel/ss_id(ss_id)/Streams(name)/Switch(ss1)/ 
this ss_id can correspond to the id of the adaptation set in DASH

**Comment by RufaelDev** [comment]
this is adopted in the spec, main use case is redundant stream ingest, I close the issue for now if no further comments
