### ISSUE TITLE
7.2.7 - CENC encryption on Profile 1 media tracks?

### ISSUE THREAD

**Issue by johndeu** [Dash-Industry-Forum/Ingest#23]
Do we really need to have CENC encryption on proflie 1 media tracks? The expectation is that the Media Processor will be doing additional work, repackaging, and re-encrypting anyways. I'm not aware of a situation that would need PlayReady or Widevine on top of HTTPS on ingest to a packager. 

Anyone else aware of a use case scenario for this?

7.2.7 Encryption specific information SHOULD be signaled
        in the [=pssh=],"schm" and [=sinf=] boxes following [[!ISOBMFF]] [[MPEGCENC]]

**Comment by RufaelDev** [comment]
I agree with this, I think this can be removed, this mainly comes from trying to harmonize with the second profile in early stage of the project, if no objection this can be removed

**Comment by RufaelDev** [comment]
I left it out of the next draft as ingesting encrypted content not yet best practice, for vod it makes sense but this is not the current spec, for live the final stream to the client/outside world will be encrypted which is what matters
