### ISSUE TITLE
DNS lookups, upload retries, and timeouts for Profile 2

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#24]
We would like to propose the following DNS lookup, upload retry, and timeout behavior for profile 2

**MANIFEST object type**
-------------------------
1. Error condition #1
-TCP connection attempt timeout
-Abort midstream
-TCP send or receive timeout

Handling
Re-resolve DNS on each retry and retry indefinitely.

2. Error Condition #2 
HTTP 5xx
Handling
Re-resolve DNS on each retry and retry indefinitely.

3. Error Condition #3
HTTP 403, 400
Handling
Do not retry - display error reason in encoder

**Data (A/V media, timed text) object type**
----------------------------------------
1. Error condition #1
-TCP connection attempt timeout
-Abort midstream
-Response timeout
-TCP send or receive timeout
-HTTP 5xx

Handling
Re-resolve DNS on each retry and continue uploading until  n seconds, where  n  is the value of segment duration. After it reaches the segment duration value, drop the current data and               continue with the next segment data. To maintain continuity of the DVR time-line, continue to upload the missing segment as a lower priority.If segment duration is low (such as 2s or 1s), uploading might exceed the segment duration time and the encoder will back up.

2. Error condition #2 
HTTP 403, 400

Handling
Do not retry - display error reason.

**Comment by KevinCJohns** [comment]
DNS retry should follow provided TTL. If the DNS response includes multiple A records, the client should cycle through each until the list is exhausted or it is able to successfully establish a connection.

For continuing to upload slow segments, this is a nice feature but for HLS, we need to call out that the encoder should not modify the Manifest post successful upload. If the Encoder 'skips' the upload and proceeds to the next segment, the manifest should have a discontinuity. Once the discontinuity is issued it cannot be redacted or the clients will stop playback. If the encoder cuts a separate program level manifest, it can make sure the missing live segment is included.

**Comment by RufaelDev** [comment]
TF: resolved in draft text , update specification recommend following TTL, add text for having short ttl domain name

**Comment by RufaelDev** [comment]
This
