### ISSUE TITLE
Define file extensions, mime type mapping and segment naming restrictions for profile 2. 

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#25]
Since the receiving origin does not parse segments upon receipt, it is useful to define a set of file extensions and mime-type mappings, so that the receiving origin can handle the media appropriately. Suggestions are:

Manifests/playlists MUST explicitly use these and only these file extensions and mime-type mappings
.m3u8 (application/x-mpegURL)
.mpd (application/dash+xml)

Any input object not having one of these file extensions will be treated as a media (video, audio or captioning ) segment. 

Naming restrictions:
Initialization segments MUST be identified through either using the .init file extension OR having the string "init" in their file name. 
All other segments which are not initialization segments MUST NOT include the string "init" in their file name. 

Recommended file extensions and mime-type mappings. 
Media Segments
.m4v (video/mp4)
.mp4 (video/mp4) 
.m4a (audio/mp4)
.m4s (video/iso.segment)
.init (video/mp4)
.header (video/mp4)
.ts  (video/MP2T)

Caption/subtitle ISO segments
.mp4 (application/mp4)

**Comment by wilaw** [comment]
We should also support the CMAF defined extensions
.cmfv (video/mp4)
.cmfa (audio/mp4)
.cmft (application/mp4)

**Comment by RufaelDev** [comment]
closed as it was address in the contribution by Will and Kevin
