### ISSUE TITLE
secure ingest

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#27]
Some discussion is needed on HTTP 1.1. over TLS and  potentially token based access between a live encoder and a receiver, see https://github.com/unifiedstreaming/fmp4-ingest/issues/7 for initial discussion
and notes from f2f: 

Mike: Mozilla is browser/client related. Kevin: should be Mozilla ServerSide recommendations. Mike: Elemental has no webserver, it’s perhaps too prescriptive. Kevin: it’s about security, so either yes or no, so SHOULD (best practice). Sam: refer to HTTP spec to let deployment choose. Kevin: HTTP 1.1 is too wide, 2 is better. Paul: 5 and 6 are too vague, should be profiled in detail. Nicol: let’s focus on important aspects. Sam: token based? Rufael: please file an issue in github so we can review in more detail, what is there came from BBC/L3, there is scope for improvement.

**Comment by KevinCJohns** [comment]
I personally don't see the issue with the Mozilla reference it is simply defining a set of allowed SSL/TLS versions and supporting ciphers, weeding out vulnerable protocols and ciphers. While Mozilla is best known as a browser, these recommendations are actually for the server side (in this case the packager) and limits what the server (packager) will negotiate based on the intersection of what the client (encoder) offers and what the server (packager) will allow.

I would propose the following updates:
5. In case HTTPS protocol is used, basic authentication MUST be supported.  The use of mutual authentication SHOULD be supported. Client certificates should chain to a trusted CA. The use of Self Signed MUST be supported.
6.  The packager MUST allow the user/operator to configure which protocols and ciphers can be negotiated. The default set SHOULD be per the mozzilla intermediate compatibility profile.

**Comment by RufaelDev** [comment]
in current draft HTTP 1.1. and TLS 1.2 TODO put in next draft
