### ISSUE TITLE
EMSG box examples and requirements (Version 1 or 0?)

### ISSUE THREAD

**Issue by johndeu** [Dash-Industry-Forum/Ingest#38]
I noticed that all of our examples for emsg and the doc show the "version=0" layout of the 'emsg' box.  Do we want to specify version=1 layout instead?  
I recall that Kilroy changed the layout in a later revision to DASH.   Version 1 of the Event Message Box is optimized for CMAF by associating the event with a media presentation time and duration (version 0 used an offset "delta" relative to the next DASH Segment’s presentation time and was primarily designed to signal DASH MPD expiration during live streaming).

**Comment by RufaelDev** [comment]
Yes, these are just examples, however the "sparse" fmp4 also holds reference time in its tfdt and it is possible to use presentation_time_delta with these reference times maintaining the dynamic range as with v1, still the "sparse fmp4" track structure can also hold version 1 emsg boxes, there is currently no constraint on het version of the emsg, but as it is not supported in examples, we should probably ad some examples and support it in the reference sources aswell. 

However, I think the timing of emsg is currently under discussion in the community, many people have difficulties with emsg and a trend/idea seems to be to use timing based on ISOBMFF as media samples, so the playback/decode time of the metadata sample (given it is a sync sample) containing the emsg is leading,  for duration the sample duration is leading etc. I think the idea is that by having the same timing model for events as for media samples a lot of confusion is avoided surrounding timescales of emsg. In CMAF tracks can have different timescales but still be synced, event tracks could be synchronized in a similar manner. This fits well with what is defined in the ingest spec right now, and I think we should encourage/follow this trend (which goes beyond this issue).

**Comment by RufaelDev** [comment]
TF call feb 13th discussion, this is mostly about the examples, there is no restriction on emsg usage
