### ISSUE TITLE
switchingset signalling

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#39]
For signalling switching sets in CMAF ingest (profile 1)

a. CMAF sect.  7.3.4 Table 11 provides the constraints on a switching set these must hold 

b. CMAF allows use of udta box and kind box  to signal a 
   scheme these must be identical amongst tracks in a switching set 

c. tsel box in udta might be considered to provide switching set group id to tracks
 
These should be incorporated in the specification, after  some discussion, 
this could solve the issue of signalling switching sets

**Comment by RufaelDev** [comment]
tracks are in a switching set it and only if:
tkhd | Shall be identical except   for width, height, creation_time, and modification_time. See NOTE 1.
trex | identical
elst | Shall   be identical except for video CMAF track files with a different composition   offset
mdhd | Shall be identical except   for creation_time, and modification_time
mehd | identical
meta | May contain different   boxes and data
udta | May contain different   boxes and data
cprt | identical
kind | identical
elng | identical
hdlr | identical
vmhd | identical
smhd | identical
sthd | identical
dref | identical
stsd | Sample   entries shall have the same codingname (four-character code), and   conform to other CMAF Track format and media profile specified constraints.   See NOTE 2.
sgpd | May differ
pssh | identical
sinf | identical
schi | identical
schm | identical
frma | identical
tenc | Shall be identical except   for Initialization Vector values
NOTE 1 Track   width and height can differ, but picture aspect ratio is the same for all   CMAF tracks.   NOTE 2 Sample   entry constraints for CMAF switching sets are defined by each CMAF media profile,   its specified or referenced ISOBMFF track format, and its CMAF switching set   constraints. A sample description can contain multiple sample entries.

These constraints are defined in CMAF, if the text in CMAF is different the text in CMAF prevails,

**Comment by RufaelDev** [comment]
Tracks are in the same switchingset if and only if:

Box | General CMAF header constraints    in a CMAF switching set
-- | --
ftyp | Shall be identical except   for media profile brands (see ‎1 in ‎7.3.4.1)
mvhd | Shall be identical except   for creation_time, and modification_time
tkhd | Shall be identical except   for width, height, creation_time, and modification_time. See NOTE 1.
trex | identical
elst | Shall   be identical except for video CMAF track files with a different composition   offset
mdhd | Shall be identical except   for creation_time, and modification_time
mehd | identical
meta | May contain different   boxes and data
udta | May contain different   boxes and data
cprt | identical
kind | identical
elng | identical
hdlr | identical
vmhd | identical
smhd | identical
sthd | identical
dref | identical
stsd | Sample   entries shall have the same codingname (four-character code), and   conform to other CMAF Track format and media profile specified constraints.   See NOTE 2.
sgpd | May differ
pssh | identical
sinf | identical
schi | identical
schm | identical
frma | identical
tenc | Shall be identical except   for Initialization Vector values
NOTE 1 Track   width and height can differ, but picture aspect ratio is the same for all   CMAF tracks.   NOTE 2 Sample   entry constraints for CMAF switching sets are defined by each CMAF media profile,   its specified or referenced ISOBMFF track format, and its CMAF switching set   constraints. A sample description can contain multiple sample entries.

The CMAF text prevails above this text, in case they are different.

**Comment by sam-geqiang** [comment]
I think we need a deterministic way to identify tracks belonging to the same switching set. One option would be to leverage the 'alternate_group' field in the 'tkhd' box as defined in ISO BMFF. Below is the definition:

alternate_group is an integer that specifies a group or collection of tracks. If this field is 0
there is no information on possible relations to other tracks. If this field is not 0, it should be the
same for tracks that contain alternate data for one another and different for tracks belonging to
different such groups. Only one track within an alternate group should be played or streamed at
any one time, and must be distinguishable from other tracks in the group via attributes such as
bitrate, codec, language, packet size etc. A group may have only one member.

**Comment by RufaelDev** [comment]
WG call thirteenth of february: some more study/investigation is needed,  switchingset constraints from CMAF do not take into account preferences of content author, alternate_group might be used for switchingsets, but what about aligned switchingsets and selection sets as defined in CMAF
