### ISSUE TITLE
F-mp4 and/or CMAF in profile 1

### ISSUE THREAD

**Issue by samgzhang** [Dash-Industry-Forum/Ingest#43]
Currently for profile 1, there a few places in the the spec that mentions both f-mp4 and CMAF as the bitstream format. Should we lock it down to just CMAF? One important consequence is that by locking it down to CMAF, it becomes a mandate that one HTTP POST can only contain one track. This is related to other discussions around stream name, track identifier and switching set.

**Comment by KevinCJohns** [comment]
2/13 WG Call, consensus of the WG was to restrict to CMAF, follow discussion will be required to determine the precise CMAF profile to be used. Our preference would be to use the CMAF Track Format, we don't need to use/restrict to the the media profiles.

Will need to update the document to remove references to fMP4 and update definition of CMAF and provide clear documentation of the relevant CMAF details.
