### ISSUE TITLE
Segment alignment of audio and video tracks

### ISSUE THREAD

**Issue by boy-vd** [Dash-Industry-Forum/Ingest#46]
I would like to raise an issue regarding the importance of segment alignment across all audio and video tracks that are part of the live ingest stream, and propose that the specification should contain some recommendations to ensure such an alignment of tracks (as much as possible).

From my understanding, there are two things that play a role when trying to attain segment alignment for audio and video. In an ideal scenario:

- Proper configuration of sample rate, frame rate, GOP, and segment length, so that audio segments and video segments have the length. For example: 48KHz sample rate, 25 fps frame rate, 48 frame GOP, 1.92 seconds segment length.
- Audio and video tracks should both start at the same time.

The first should normally be configurable for each stream, but of course there are many scenarios that are less than ideal, such as when working with dropped frame frame rates. I don't see a solution for such scenarios, other than accepting audio and video tracks that are not aligned at each segment.

The second may be more a of point of discussion: would the ideal of both audio and video track starting at the same time be something that could be recommended, or even required? If not, could there be a recommendation or requirement of how to deal with any offset of audio versus video or video versus audio?

**Why is this important?**
For those who may doubt the importance of segment alignment between audio and video, consider the following use cases:

- Virtual subclips that are generated from a live stream for catch-up and start over services. With no alignment and no transcoding, these clips may have either audio or video starting earlier, which may lead to problematic player behavior.
- On-demand clips are captured from a live stream for nPVR solutions, highlight selection or other workflows that make use of such clips. Same as with the use case above, with no alignment and no transcoding these clips may have either audio or video starting earlier, which may lead to problematic player behavior.

**Comment by RufaelDev** [comment]
Both in the ingest spec and in the CMAF specification tracks start at the same time, so this is already supported in the specification
