### ISSUE TITLE
Sparse track to emsg-containing track mapping

### ISSUE THREAD

**Issue by samgzhang** [Dash-Industry-Forum/Ingest#48]
In CMAF ingest (interface 1), active processor needs to convert incoming sparse track payload into emsg boxes to be embedded in CMAF fragments/chunks. Do we need to specify which switching set should contain emsg boxes for a particular sparse track? Or is the active processor free to pick any video/audio switching set?

**Comment by RufaelDev** [comment]
Right now the ingest spec considers presentation level metadata only, not per switching set. The active media processor could be free to make a decision, but the ingest spec assumes the metadata is related to the media presentation and/or live channel. This maps to the use cases envisioned, such as interactivity metadata (e.g. VAST events), program/splicing information (signalled via SCTE-35), personalized metadata relating to the presentation time etc. What use cases would per switching set metadata apply ? Many of the configuration of switching sets can be achieved with the single initialization CMAF Header, what other metadata is needed at the switchingset level ?

**Comment by RufaelDev** [comment]
Discussed in call 28th of march:

1. metadata is presentation specific 
2. the packager can decide where to carry (audio/video/mpd event), this is packager administrator/configuration, this can go to the implementation guidelines in the next phase
