### ISSUE TITLE
Token auth

### ISSUE THREAD

**Issue by samgzhang** [Dash-Industry-Forum/Ingest#49]
In Section 5 "General Ingest Protocol Behavior", basic auth and cert auth was mentioned. Should we also mention or recommend token auth?

**Comment by RufaelDev** [comment]
This makes sense, do you have some specific text in mind to add to the document ? We can also discuss in the next call

**Comment by RufaelDev** [comment]
Discussed in the call on 27th of march 

- in principle this is something that can be added but more work is needed and interoperability needs 
to be guaranteed 
- look at the DASH-IF TAC solution 

for now we will not explicitly support it in the spec, but it should be considered for future revision

**Comment by RufaelDev** [comment]
according to Nicolas, HTTP Digest authentication seems sufficient, shall we add HTTP Digest Authentication ?

**Comment by RufaelDev** [comment]
HTTP digest authentication is most practical solution for now.

**Comment by RufaelDev** [comment]
removed the reference to token base authentication, for simplicity we stick to HTTP Digest Authentication in this specification, and optionally basic auth/ client side tls certificates
