### ISSUE TITLE
General Ingest Protocol Behavior

### ISSUE THREAD

**Issue by KevinCJohns** [Dash-Industry-Forum/Ingest#55]
Requirement 10 - The HTTP POST for sparse data SHOULD be short-lived, terminating as soon as the data of a fragment is sent.

This appears to be specific to interface 1. Since General Ingest is meant to apply to both interface 1 and 2, it may be better to move this requirement to the General Protocol Requirements section under Interface 1.

**Comment by RufaelDev** [comment]
is there n sparse post of data in interface 2 ? What about chunked transfer in interface 2 of sparse data ? would it not make sense to also use multiple short running post/put commands in this case ?

**Comment by KevinCJohns** [comment]
I don't believe HLS has sparse data, will have to look into whether DASH has such a concept. Interface 2 does cover the use of chunked transfer already.

**Comment by RufaelDev** [comment]
For example in DASH timed text tracks (subtitle tracks) can be sparse, it would not make sense to keep the connection open all the time and i would imagine that for such a track multiple post/put could be used to upload a timed text track ? some subtitles only occur in a few parts of the presentations making them sparse. This is more a general recommendation as to avoid resource usage by open connections that do not actually send data, in HLS there are also fragmented text tracks that might be sparse in some cases.
