### ISSUE TITLE
Illustrative Example of using CMAF and DASH ingest specification

### ISSUE THREAD

**Issue by KevinCJohns** [Dash-Industry-Forum/Ingest#58]
I am a bit confused by the second example in this section. I read it to be an example of interface 2 whereby the ingest source does the required content packaging and manifest generation and the media processor (origin server) is a simple origin. However it states:

To receive the stream as a CMAF ingest for re-packaging at the origin the following steps can be applied.
1. Ignore the DASH Manifest
2. Ignore the segment names, only look at the relative path to identify the stream names
3. Ignore the HTTP Delete commands

What is meant by this statement? A MPE implementing interface 2 wouldn't follow those steps. Is it trying to describe how interface 2 can be used interchangeably with interface 1? If so, it would be good to clarify that?

**Comment by RufaelDev** [comment]
Hi yes, in many use cases people want to repackage a dash stream, for example to add encryption or to also support HLS, I will add additional information about this use case
