### ISSUE TITLE
numbering of segments in interface 2

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#62]
Interface 2 states in 7.1.3.5 

The Ingest Source MUST include a number which is monotonically increasing with each new Media Object at the end of Media objects name. It MUST be possible to retrieve this numeric suffix via a regular expression. A common method is to use the time at which the Media Segment was created divided by the Media object duration.

some comments/concerns raised in call on 24th of April: 
- what if ad inserted content with different numbering ? 
- what if filename includes a number ? 
- how would the regular expresssion be, addional explanatory text would be useful ? 
- this introduces additional constraints to the live encoder, reducing implementation 
  freedom

This text needs to be updated, and/or additional supporting information needs to be added
such that it will be clear that the encoder can chose different filenames and different modes operations.

discussion/feedback is appreciated

**Comment by wilaw** [comment]
It looks like this text has been confused during assembly and import. The original language of "A common method is to use the time at which the Media Segment was created divided by the Media object duration." was mine. However it did not apply to the preceding text. What is does apply to is the separate requirement that each media segment have a unique path+filename.

To answer the questions posed in this thread:

    1. "what if ad inserted content with different numbering ?" - that is fine. The requirement for  segment names to include a monotonically increasing suffix should be relaxed in  HLS across discontinuity markers and in DASH across periods. The spec language should be amended to indicate this. 
2. "what if filename includes a number ?" - that is fine as long as it is separated from the numeric suffix by a non-numeric character.  For example video-1920x1080-46532.mp4 is acceptable whereas video-1920x108046532.mp4 is not. 
3 "how would the regular expression be, additional explanatory text would be useful ?" - the exact regular expression need not be defined by this spec, although it would be something along the lines of var matches = str.match(/\d+$/);
4. "this introduces additional constraints to the live encoder, reducing implementation freedom" - the majority of encoders already support this requirement today.

**Comment by RufaelDev** [comment]
Thanks for additional input, it is a good start, but I have a few remarks that need to be resolved:
0. "A common method is to use the time at which the Media Segment was created divided by the Media object duration" -> in case of variable duration may this not result in equivalent numbers, or even decreasing numbers, this text/requirement does not look good me. 
1. -> relaxing is fine but that means a SHOULD instead of a MUST, we will then define the alternative cases like period boundaries, inserted ad content, or other, otherwise it can be a MAY statement
2. it should be exactly defined what is allowed and what not, that should be the goal of an interop specification, if implementations exist today please provide the example/used naming schemes, and what is allowed and what not 
3. the regex would also help to understand what is allowed and what not, it is needed for interoperability
and alternative implementations 
4. ok, but it needs to be documented accurately in the specification allowing implementation based on the text and not only implementations that exist today, further you just proposed a different requirement then what was in the text so which requirement are you referring to exactly ?

**Comment by RufaelDev** [comment]
resolved in call 8th and the spec was updated
