### ISSUE TITLE
General usage for Ingest in DVB ABR Multicast

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#65]
We tried to map the Ingest Spec to be used in the DVB ABR Multicast architecture of DVB at the interface Pin, especially but not only with low latency. However, the spec as is is not usable, neither interface 1 nor interface 2. We also consider that Ingest is important for 3GPP xMB interface, but not useful either. We encourage to fix this and will try to support as much as possible.

**Comment by RufaelDev** [comment]
awaiting feedback from dvb otherwise close by next call 18 sept.

**Comment by RufaelDev** [comment]
TF 18 september: no input received, close. reopen in case there is more input. Spec can be used as is.
