### ISSUE TITLE
Interface 1 and 2

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#66]
Interface 2 is clearly set apart from Interface 1 in clause 7, except for a very vague statement: "In case [!MPEGCMAF] media is used, the media track and segment formatting will be similar as defined in Interface 1."

We consider it important that the spec in itself is more consistent and that both interfaces are harmonized and we use CMAF on both interfaces. Hence, we encourage to provide more details on how the two relate and make them more integrated.

**Comment by waqarz** [comment]
Directly related is this statement, this also needs consolidation:

"In this case the ingest source implements interface 2 DASH ingest. But as in this case the DASH presentation uses CMAF, the media and track constraints of interface 1 are also satisfied"

**Comment by RufaelDev** [comment]
In case CMAF is used in interface 2 both interfaces use the same track and segment formatting, namely the one defined in CMAF. The sentence can be improved in next editorial update to articulate this more clearly.
transport streams deprecation was discussed:
see: https://github.com/Dash-Industry-Forum/Ingest/issues/54
There was also some work in harmonizing the HTTP response codes: 
https://github.com/Dash-Industry-Forum/Ingest/issues/63 
so convergence is progressing on these two key aspects.

**Comment by RufaelDev** [comment]
There was harmonization, an example was added. we can close this, once cmaf+dash binding is defined
