### ISSUE TITLE
Low Latency

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#67]
There is no specification to enable low-latency DASH+CMAF delivery: there is no mention of using a HTTP chunk transfer mode in clause 7. This is an important use case and needs more consideration.  Some of the features that we are more looking for (low latency, MPD updates) are insinuated in the example (also using Nicolas' workflow example) in Section 8, but this is not consistent with Clause 6 and 7.

More work is necessary and we want to support this.

**Comment by RufaelDev** [comment]
added the low latency chunked HTTP transfer in interface 2, this should be supported indeed
