### ISSUE TITLE
Styp

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#69]
Interface 1 recommends against using styp box and hence the signalled brands therein: "CMAF Tracks SHOULD NOT use segmentTypeBox to signal CMAF Media object brands like chunk, fragment, segment."

We are strongly against this as this prohibits the use of simple detection of what chunk it is. In particular, we have 3 chunks (following TUC), fragment, random access and regular chunk. We need random access for easy detection of boundaries.

Throughout the specification (both for Interface 1 and Interface 2), there is no provisioning or mentioning of RAP chunk signalling or a last chunk in a segment. 

Also there is one issue, namely that the receiving entity must add a CMAF chunk delay to become aware of the last chunk in a segment (as the POST of a segment succeeds) unless there is marker somehow for this.

**Comment by RufaelDev** [comment]
I proposed this aswell in, https://github.com/Dash-Industry-Forum/Ingest/issues/35 but experts conside it not necesary when it was discussed
