### ISSUE TITLE
Update terms

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/Ingest#71]
> The CMAF track MAY comprise CMAF chunks [MPEGCMAF] which are moof mdat structures that may not be an _instant decoder refresh (IDR)_ or bit rate switching point

to CMAF terminology

The CMAF track MAY comprise CMAF chunks [MPEGCMAF] which are moof mdat structures that may not be a CMAF Random Access chunk or bit rate switching point [?? the latter needs check]

**Comment by RufaelDev** [comment]
please propose improved text then it can be updated
