### ISSUE TITLE
ingest source behavior on 30x HTTP response

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#77]
#75 support for redirect response codes (30x). However, what should the default behavior of the ingest source be ?

**Comment by RufaelDev** [comment]
call 12th of June: please provide more information on the use cases for using 30x responses

**Comment by ylbao** [comment]
Hi Rafael,

This is used in redirecting encoder to another URL at the beginning of a stream. Encoders currently usually do not support this. I would suggest to remove this suggestion.

Thanks,
Yiliang

**Comment by RufaelDev** [comment]
ok thank you, it will be left out then
