### ISSUE TITLE
Conversion of Ingest Metadata to DASH-IF content offering

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#8]
It is recommended that we create implementation guidelines on how the Ingest Metadata can be interpreted by a DASH packager and how it can use it in the Media Presentation offering.

**Comment by RufaelDev** [comment]
I added the example tool fmp4DashEvent to convert a metadatatrack with emsg boxes to an opaque dash/xml eventstream you can try by fmp4DashEvent scte35.ismv out_example.xml converting an emsg sparse track to a DASH emsg.

**Comment by KevinCJohns** [comment]
Should also include/consider .m3u8 for HLS.

**Comment by RufaelDev** [comment]
What I understand the DASH binding for CMAF explicitly does this, would it be ok to refer to that ?

**Comment by RufaelDev** [comment]
see CMAF DASH Binding ?

**Comment by RufaelDev** [comment]
TF 18 sept: leave for DASH/CMAF binding
