### ISSUE TITLE
High-level community review comments 

### ISSUE THREAD

**Issue by rayvbr** [Dash-Industry-Forum/Ingest#82]
I did a read-through of the entire document. See below for my high-level comments. I'll open separate issues for the more technical comments. 

General
- ‘Receiving Entity’ and ‘Media Processing Entity’ seem to be used interchangeably throughout the document. Are there any requirements that apply only to one or the other? If not, my suggestion would be to only use Receiving Entity in all normative text, and in informative text be very clear when one or the other is meant. 
- The spec has normative text for both the Ingest Source as well as the media format. It is unclear whether it is also supposed to mandate behaviour in the Receiving Entity (is that within scope anyway?). In a lot of cases, it is unclear how the Receiving Entity is supposed to respond in case an Ingest Source does not properly implement a SHALL/MUST. Most sections do not contain any normative behaviour on the Receiving Entity side (e.g. 5.3) 
- Informative sections need to be clearly marked as such. In the current document, especially for interface 1, it is sometimes unclear whether a paragraph is normative or informative. 5.1 for example looks informative, but contains some text that could be construed as being normative
- Overall, the text for interface 2 seems significantly more ‘mature’ than that of interface 1
- There are several elements of interface 2 that could clearly also be useful for interface 1 (e.g. section 6.1.2). Is there any reason why the two interfaces don’t share such common elements?

Section 5.1:
- Should the right side of diagram 8 be Receiving Entity instead of Media Processing Entity?
- Diagram contains some error flow which are not defined nor explained in the accompanying text
- For readability, it may be good to split this section up into several sections and clearly define what the purpose of each sub-section is (informative, normative, example, etc.)

Section 5.2;
- Bullets 9-14 seem to belong in 5.3 instead of 5.2 given that they seem to specify the media format instead of the protocol
- No normative aspects on Receiving Entity? 
- Interface 2 explicitly defines how POST and PUT can be used interchangeably, why not do the same thing here?
- Are mime types at all relevant here? (given that they’re specified for interface 2 in section 6.1.3, but not for interface 1)

Section 5.3:
- This section contains a lot of SHOULDs for which it is unclear what happens if they’re not met. Are they just recommendations? If so, maybe it would make more sense to mark them as RECOMMENDED instead of SHOULD (see RFC2119, which is being referenced by the Conformance section in this document, on the difference between SHOULD and RECOMMENDED)
- Spec is not clear what happens if media tracks contain ISOBMFF boxes not specified in CMAF. Is it such a stream still considered valid? Is it mandatory for a Receiving Entity to pass those boxes through unchanged? Or is it allowed to drop them? I think this is a very important aspect that will determine the future-proofness of this document
- “Fragment durations SHOULD be between approximately 1 and 6 seconds”. This statement seems very out-of-place in a spec like this. 
- Bullet 5: I have difficulty parsing what exactly this bullet is supposed to mandate
- Bullets 9 and 10 should probably be part of a single item. Also, it is not exactly clear what the normative nature of both statements is, unless the goal is to say that a Receiving Entity SHALL support both in-band and and header-based parameter sets. In that case, these bullets should be rephrased as such.
- Bullet 12: Given that CMAF ingest is supposed to be manifest-agnostic, why is there a MUST for the udta box to contain a dash schemeID?

Section 6.1.2: 
- Seems to contain some good best practices. Why does this text not apply to Interface 1 as well?

Section 8:
- Seems like a left-over from an IETF template where this section is required. Why is it present in this document?

**Comment by RufaelDev** [comment]
Comments have been addressed in the specification. Excluding following:
- specification is using CMAF so non CMAF boxes are not supported 
- specifying fragment durations is important for ingest, so this is not altered
- dash scheme is used to signal track roles, this is important for example for subtitles and timed text
- SHOULDs imply shall, but due to nature of protocol they are not always satisfied (e.g. out of order arrival in case an instance is restarted and resends a fragment), overall SHOULDs should be implemented for conformance purpose.

**Comment by RufaelDev** [comment]
Thanks, we updated the specification, this issue will be closed
