### ISSUE TITLE
Document title

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#9]
Current title is "Guidelines for Implementation: DASH-IF Ingest". 

I suggest that this should be a specification rather than a collection of guidelines. It also applies to media beyond DASH. Therefore a more appropriate title may be

"Media Ingest Specification"

**Comment by RufaelDev** [comment]
Will change to the old title as discussed in the meeting, name was based on what was available in the template draft

**Comment by RufaelDev** [comment]
consensus was: live media ingest
