### ISSUE TITLE
Extend Community Review until Sep 5, 2019

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#91]
It is suggested that the review is extended until Sep 5. There are multiple reasons:
- alignment with MPEG 4th edition
- alignment with LL-DASH
- alignment with Ad Insertion CR
- alignment with 2nd edition of CMAF

It was also impossible for those working on the editing to contribute to the review.

**Comment by RufaelDev** [comment]
yes, review period was extended. 
- LL DASH -> we support chunked cmaf + prft is supported, IBC showed demos of combining CMAF ingest with DVB DASH LL and HLS LL
- Ad insertion is aligned (encoding of splicing)
- 2nd edition CMAF -> we are independent of media profiles 
- DASH fourth edition -> we do not use most DASH constructs explicitly , no changes expected for both interfaces.
