### ISSUE TITLE
Comments on 2)

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#93]
https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#conventions

1) Why is CMAFStream defined? Is the term CMAF Track file not sufficient?
2) What is meant by "application" in the Event received Time?
3) "Live Stream Event": Event is confusing, propose to use Session
4) adaptationset -> Adaptation Set

**Comment by RufaelDev** [comment]
- Adding more explanation, cmaf stream -> header resender, separate tcp connections, bytestream format, should be increasing tfdt except in case of reconnect requirement shall
- application, receiving entity
- consider changing to session
- ok

**Comment by RufaelDev** [comment]
For the next commit:
- changed all media processing entity to receiving entity 
- improved definition of CMAF stream as discussed 
- changed live stream event to live stream session
