### ISSUE TITLE
Comments on 5)

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#94]
https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#profile_1

1) "adhere to the general requirements." Please provide reference to the requirements

https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#profile_1_general

2) CMAF file => CMAF Track File. Or do you want to say to an ISO BMFF file?
3) Diagram -> Figure. And make Figure captions below figure
4) It is confusing to call the moof box as metadata. You may call it index information.
5) What does it mean "can sometimes referred to as a [MPEGCMAF] header."?
6) "The combination of moof mdat can be referred as a CMAF fragment or CMAF chunk or a CMAF segment" is not correct. A CMAF Fragment has very well defined properties and not any moof/mdat pair can be referred to as CMAF Fragment.
7) "These CMAF Addressable media objects can be jointly referred to as CMAF Media object" This is unclear and should be removed.
8) "Diagram 6 illustrates the synchronization model," Synchronization Model for what? Does this spec define one? Why not just used exactly what is defined in CMAF? 
9) "For synchronization of tracks coming from different encoders, sample time accuracy is required. i.e. the same samples need to be mapped to the sample time on the timescale used for the track." What does this mean. Is it a requirement for encoders?
10) Diagram 6 shows the CMAF Presentation Model and should make it clear and reference CMAF clause 7.3.6
11) Diagram 8 and the text around is independent of CMAF and should be treated separately.
12) "Diagram 8 shows the sequence diagram of the protocol. It starts with a DNS resolution (if needed) and an authentication step (using Authy, or TLS certificates) to establish a secure TCP connection. While this specification promotes TLS certificates, in future versions using token based authentication will be considered. " What does this mean in terms of implementation? Please make the statement much clearer.
13) "At the end of the session, for tear down the source may send an empty mfra box to close the connection and Publishing point ... " Is this a requirement? Recommendation? It would be good to make this more explicit.

https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#general_Protocol_Requirements_p1
14) In 5.2 it is unclear what the context is. Can we write an assumption section, for example: POSTURL is known, 
15) Is RFC2626 correct? Should it be HTTP/1.1?
16) Requirement 11 - this is not a protocol issue, but needs to be part of the format.
17) Requirement 12 - this is also not a protocol issue. In addition it is unclear how the Media Processing engine would know which tracks are part of a Switching Set. This has been addressed in the LL CR.
18 ) If we have 13, why do we need 5.3? How does Req 13 relate to 5.3?
19 Req 14. the sentence after "However, ..." is unclear. please delete
20) The NOTE: please add an explicit reference to the section.

https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#Requirements_for_formatting_Media_Tracks

see next issue

**Comment by RufaelDev** [comment]
Thanks for the comments & review: For the next commit:
1,2,3,4) done 5) changed text (removed sometimes) 6) amended 7) done (removed) 8) explicitly referenced CMAF synchronization model, this spec re-uses that 9) yes clarified 10) done 11) ok, made a separate paragraph 12) removed it (it will be unlikely tokenauth will be added and we will consider only basic authentication) 13) this is later in the normative sections explained 14) added this section reference the definitions for POST_URL and Publishing point 15) corrected 16) renamed the section to include formatting 17) same 18) added that the next sections will define additional constraints, these are not in cmaf and are mainly useful for packaging 19) removed 20) done
