### ISSUE TITLE
Comments 5.3)

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#95]
Please find comments in _italics_ on each of the bullet point: https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#Requirements_for_formatting_Media_Tracks

_First of all an overall question. Are these requirements for a media track to be used in the ingest or are these assumptions under which they can be used. I consider more the latter, but if we want to define requirements for media tracks as it seems, then please find suggestions below._

Media tracks SHALL be formatted using boxes according to section 7 of [MPEGCMAF] except for section 7.4. which dictates boxes that are not compliant to [ISOBMFF] relating to encryption and DRM systems

_The sentence should be simplified. Media Tracks shall conform to CMAF Tracks as defined in [MPEGCMAF] with the following exception: ..._
_ The exception is completely unclear and needs to be very explicit._

The trackFragmentDecodeTime box tfdt box MUST be present for each fragment posted.

_This is a consequence for CMAF. Do you want to say: Every posted fragment shall conform to a ..._
_Options for conform are: CMAF Addressable Resource, CMAF Fragment, CMAF Chunk, ???_

The ISOBMFF media fragment durations SHOULD be constant, the duration MAY fluctuate to compensate for non-integer frame rates. By choosing an appropriate timescale (a multiple of the frame rate is recommended) this issue should be avoided.

_Why ISOBMFF now? We use fragment, CMAF Fragment and so on. Is this a requirements for each CMAF chunk or each CMAF Fragment? What is you want to align CMAF Fragment boundaries with splice points. This must be permitted._

The fragment durations SHOULD be between approximately 1 and 6 seconds.

_Which fragments are you referring now?_

The CMAF Tracks SHOULD use a timescale for video streams based on the framerate and 44.1 KHz or 48 KHz for audio streams or any another timescale that enables integer increments of the decode times of fragments signalled in the "tfdt" box based on this scale. If necessary, integer multiples of these timescales could be used.

_Do you mean Media Tracks? This requirement is unclear. What would I do if I write a conformance checker? This would help a lot_

The language of the CMAF Track SHOULD be signalled in the mdhd box or elng boxes in the init fragment, cmaf header and/or moov headers (mdhd).

_What is the init fragment? mdhd and elng are well documented, so unnecessary to speak about the the placement._

The CMAF track MAY comprise CMAF chunks [MPEGCMAF]

_What does this mean? This is according to CMAF, but it is unclear what it means for the requirements here._

For video tracks, profiles like avc1 and hvc1 MAY be used that signal the sequence parameter set in the CMAF Header. In this case these codec parameters do not change dynamically during the live event.

_Change: during the live event -> in the Media Track_

In case the language of a track changes, a new CMAF Header with updated mdhd and or elng SHOULD be send.

_ This operation is confusing. Generally, can one send a new CMAF Header? What can change in the header?_

Track roles SHOULD be signalled in the ingest by using a kind box in userData udta box. The kind box MUST contain a schemeIdUri urn:mpeg:dash:role:2011 and a value containing a Role as defined in  [MPEGDASH]. In case this signalling does not occur processing entity can define the role for the track independently.

_Isn't this a requirement in CMAF?_

Note: [MPEGCMAF] has the notion of a segment, a fragment and a chunk. A fragment can be composed of one or more chunks, while a segment can be composed of one or more fragments. The Media fragment defined here is independent of this notion and can be a chunk, a fragment containing a single chunk or a segment containing a single fragment containing a single chunk. In this text we use Media fragment to denote the structure combination moof mdat, corresponding to a CMAF fragment or chunk.

_This note should be used upfront and should be a definition. The conformance requirements are unclear. As stated in the beginning, a much clearer conformance statement to CMAF is preferred._

**Comment by RufaelDev** [comment]
Thanks for the comments. In the next commit the suggestions are adopted: 
1) clarified the exception, CMAF track is supported but not CENC related aspects 
2) 3) ISOBMFF fragment was used as generalisation it is also defined in the spec, however currently
      -> all 'fragment' changed to only to CMAF fragments 
     ->  cmaf chunks need to be signalled with SegmentType 
           (only if not coincide with fragment start), as to allow the receiver to detect them 
           and have a semantic for them in the protocol. I added this to the requirements 
           on cmaf chunks.

Resending of CMAF Header for language change and parameter sets is clarified 

The usage of kind box for role signalling is specific to this specification for DASH subtitles/media,
and was based on discussions in this group. 

moved the note to the beginning of the section.
