### ISSUE TITLE
Comments on 5.5

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#97]
https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#timed_text_and_subtitle_streams

For the whole section it is unclear to what extent this is an overlap with clause 11 of CMAF. Please remove and duplicated requirements.

**Comment by RufaelDev** [comment]
For the next commit:
removed the overlap with CMAF, what is additional to CMAF is kept 
  - role signalling
  - language changes
  - bitrate signalling 
in addition webVTT and TTML XML brands are preferred for the ingest.
 
Note that CMAF itself is also buggy and implementing is not easy, as you need to 
read MPEG-4 30, CMAF, ISOBMFF which are not freely available. This makes it very hard for 
implementers. One bug in CMAF is the ommision of nmhd in Table 3 this is mandatory for webVTT , and is derived from ISOBMFF specification. In any case for compactness the duplication is removed and only the additional requirements on timed text tracks are kept

**Comment by RufaelDev** [comment]
comments were adressed
