### ISSUE TITLE
Example for Common Ingest is missing

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#98]
It seems that a key issue is the ability of uploading media content once, but then using HLS and DASH manifest for distributing the same content. Is this addressed?

**Comment by RufaelDev** [comment]
I believe this is the first example in the specification (using interface 1 CMAF ingest), but such an example using interface 2 would be interesting. I think this would require selection of the right profile for DASH and HLS such that they reference the same CMAF media content.

**Comment by RufaelDev** [comment]
first example covers this
